name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Deploy to server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 192.168.1.1          # Replace with your server IP or domain
          username: root             # Replace with your SSH username
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            YourPrivateKeyHere
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            cd /var/www/my-nodejs-app
            git pull origin main
            npm install
            pm2 restart app
